title: Md. Tarikul Islam
name: Md. Tarikul Islam
email: tarikul.geb24@gmail.com
description: >-
 Master’s Student in Genetic Engineering and Biotechnology at University of Rajshahi.
 Passionate about oncology, natural compounds, and medical biotechnology.
Seeking Master's/PhD opportunities in cancer research, bioactive phytochemicals, or Biotechnology
baseurl: ""
